name: Update Portainer Stack

on:
  push:
    branches: [ "main" ]

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Update Service via Webhook
        uses: newarifrh/portainer-service-webhook@v1
        with:
          webhook_url: ${{ secrets.PORTAINER_WEBHOOK_URL }}
          
